### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by Schwagersan** [FloEll/CWSI#3] opened 2021-07-30 10:13 UTC
Hello, 

I am using thermal data captured with a UAV. I have processed the thermal orthomosaic. Now I am using  it at QGIS. I have an orthomosaic where each pixel has its own temperature information. The range of the temperature values is large, but when I use the plugin and only use the daytime temperature, I only get values between 0.99 and 1 as a result. However, this cannot be right. Can it be that the plugin does not always work with only the daytime temperature input and that I also need Twet and Tdry?

Best regards

**Comment by FloEll** [comment] 2021-07-30 11:29
Hi Schwagersan, 
thanks a lot for reporting this issue. 
Yes, that sounds like a rather weird result! Are your input temperatures in Kelvin, Fahrenheit or °Celcius? Can you maybe send me your thermal orthomosaic (or a part of it if it is really big) and the air temperature? So I can try to reproduce this and figure out the issue? 
Generally, if you have Twet and Tdry, your result will most likely be better, but it should already give a good estimate without these values though. 
Best

**Comment by Schwagersan** [comment] 2021-07-30 11:39
Hello,

Thank you for the quick reply. I would be very happy to have your help. The data is in °Celcius. The Orhtomosaic has a size of 14.6MB. Is that too big for you? 

Best regards

**Comment by FloEll** [comment] 2021-07-30 12:27
Hi, 
no, that is fine :) You can put it either in a dropbox (or sth similar) and post the link here, or you can send it to info@ecothermographylab.com . 
Best wishes and have a nice weekend!

**Comment by Schwagersan** [comment] 2021-07-30 12:46
Hello,

I sent a WeTransfer link to the email address. Tair was 28.68 °C. Thank you very much and have a nice weekend too.


Best regards

**Comment by FloEll** [comment] 2021-07-31 06:42
Hi Schwagersan, 
thanks for sending me your .tif file via WeTransfer. As you can read in the plugin Info-tab: "The image should be a one/single band .tif image and each pixel should represent a temperature measurement." However, your .tif map has three bands. Your temperatures are not represented in actual values, but in colors (the 3 RGB bands). I took a screenshot of this here:

![3_Bands_IndexColor](https://user-images.githubusercontent.com/48258911/127731128-9eea61be-bbec-411f-9a31-ae1286142d72.PNG)

This is a screentshot of what it should look like (single band raster with Temeratures (here in Kelvin) for each pixel).

![1-band](https://user-images.githubusercontent.com/48258911/127731248-d111526e-3eca-4e01-82f2-e1a86260ca6e.PNG)

Since the plugin did work for you, but just delivered the wrong results, did you maybe accidentally send me the RGB instead of the one-band file? 
Best

**Comment by FloEll** [comment] 2021-08-01 15:00
Hi, 
thanks for sending the one band data 👍 You are right, if you run the whole map, the results are very strange. 
I looked a bit into the image and what might cause this. Then I realized, that the map includes what looks like a river or lake and a roof. 
If you don't input the Twet and Tdry values, the CWSI is calculated on a somewhat reduced model. Twet and Tdry are usually the measurements that make the CWSI very realistic or very well connected to the actual environment. So far, we tried it with crop maps of oil palm and winter wheat and a few forest and agro-forestry sites. It usually worked well also without the input of Twet and Tdry. However, we never had many artifacts (like roof tops and cars) in the map. We also never had open water spaces in the images. I once used some evaporation pans for calibration tests, but masked them out when I was running a model with the data, because it was also giving weird results. 
I tested this just removing the river and the house and cars using a mask shapefile:
![Masked_image](https://user-images.githubusercontent.com/48258911/127775322-851e5bdf-de97-445d-883a-5ad9b4712559.PNG)

The mask is not very accurate, sorry for that. But I think you'll get much better results if you cut open water and artifacts from the map and keep just the vegetation and soil. 

Hope that helped you a bit. I'm happy you came up with the issue, I made a note for the next version of the CWSI plugin. Maybe I'll implement something to remove extreme outliers/ or obvious artifacts. I would be happy to hear back from you if you could get more plausible results. 

Btw. I just saw the huge glider in the map. I'm a big fan of wooden gliders!! I didn't have much time to fly or let alone build new ones in the last years, but great hobby!!

**Comment by FloEll** [comment] 2021-08-03 06:36
Did masking out the open water and artifacts work for you? 
Can we close the issue or should we try something else?

**Comment by Schwagersan** [comment] 2021-08-03 14:09
Hello,

thanks for your help. After following your steps, the results were perfect.

Best regards

**Comment by FloEll** [comment] 2021-08-04 06:47
I'm very happy to hear that! I'll close this issue now, but if you encounter any other difficulties, just contact me again. 
You can also check out my other QGIS plugin to calculate evapotranspiration from thermal images: QWaterModel 

Best regards

**Closed as completed** 2021-08-04 06:47 UTC
